version: '2'

networks:
  composer_default:
    external: true

services:
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - composer_default
    ports:
      - 27017:27017
  composer-rest-server:
    container_name: composer-rest-server
    build: ./
    networks:
      - composer_default
    ports:
      - 3000:3000
    environment:
      - COMPOSER_CARD=restadmin@blockchain-network
      - COMPOSER_NAMESPACES=never
      - COMPOSER_AUTHENTICATION=true
      - COMPOSER_MULTIUSER=true
      - 'COMPOSER_PROVIDERS={ "github": { "provider": "github", "module": "passport-github", "clientID": "9e96642182047b169c01", "clientSecret": "b698d344286a76ce4233b4f81e201139df11c55e", "authPath": "/auth/github", "callbackURL": "/auth/github/callback", "successRedirect": "/", "failureRedirect": "http://localhost:4200/login" } }'
      - 'COMPOSER_DATASOURCES={ "db": { "name": "db", "connector": "mongodb", "host": "mongodb" } }'
    volumes:
        - ~/.composer:/home/composer/.composer
    depends_on:
      - mongodb
